settings:

  bookingPage:
    type: page
    label: 'Booking Page'
    description: 'Select the page where the booking form is displayed.'
    default: 0
  bookingPid:
    type: page
    label: 'Bookings Data'
    description: 'Select the folder where the booking form data is stored.'
    default: 0
  detailPage:
    type: page
    label: 'Detail Page'
    description: 'Select the page where the room details are displayed.'
    default: 0
  roomsPage:
    type: page
    label: 'Rooms Page'
    description: 'Select the page where the rooms are displayed.'
    default: 0