settings:

  bookingPage:
    type: page
    label: 'Booking Page'
    description: 'Select the page where the booking form is displayed.'
    default: 0
  bookingPid:
    type: page
    label: 'Bookings Data'
    description: 'Select the folder where the booking form data is stored.'
    default: 0
